version = 0.1

[default.deploy.parameters]
stack_name = "lambda-ping"
resolve_s3 = true
s3_prefix = "lambda-ping"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
